name: recsys_autoencoders
channels:
  - defaults
dependencies:
  - python=3.6
  - cloudpickle=0.6.1
  - numpy=1.16.4
  - pandas=0.24.2
  - scikit-learn=0.20.1
  - seaborn=0.9
  - click=6.7
  - tensorflow-gpu==2.0
  - scipy=1.2.1
  - graphviz
  - pydotplus
  - pip:
    - mlflow
